# Generated by Django 5.0.2 on 2024-12-02 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('whatsapp_group_invite_link', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('NOTE', 'Note'), ('CAT', 'CAT'), ('ASSIGNMENT', 'Assignment')], default='NOTE', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informatics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informatics.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('NOTE', 'Note'), ('CAT', 'CAT'), ('ASSIGNMENT', 'Assignment')], default='NOTE', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informatics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informatics.semester')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
