# Generated by Django 5.0.2 on 2024-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatics', '0003_semester_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='name',
            field=models.CharField(default='document', max_length=255),
        ),
    ]
