# Generated by Django 5.0.2 on 2025-03-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatics', '0010_alter_documentcontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
