# Generated by Django 5.0.2 on 2025-03-18 08:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatics', '0011_alter_documentcontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcontent',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='document'),
        ),
    ]
